spring.application.name=schedule-service

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.root=INFO

spring.datasource.url=jdbc:postgresql://${SCHEDULESERVICE_POSTGRES_HOST:localhost}:${POSTGRES_PORT:5442}/${POSTGRES_DB:well4you}
spring.datasource.username=${POSTGRES_USER:user}
spring.datasource.password=${POSTGRES_PASSWORD:1234}

spring.jpa.properties.hibernate.default_schema=scheduleservice
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.sql.init.mode=always

notification.service.name=${NOTIFICATION_SERVICE_NAME:localhost}
notification.service.port=${NOTIFICATION_SERVICE_PORT:8082}

user.service.name=${USER_SERVICE_NAME:localhost}
user.service.port=${USER_SERVICE_PORT:8089}

coach.service.name=${COACH_SERVICE_NAME:localhost}
coach.service.port=${COACH_SERVICE_PORT:8085}

image.service.name=${IMAGE_SERVICE_NAME:localhost}
image.service.port=${IMAGE_SERVICE_PORT:8083

server.address=0.0.0.0
server.port=${SCHEDULE_SERVICE_PORT:8090}
