spring.application.name=comment-service

spring.datasource.url=jdbc:postgresql://${COMMENTSERVICE_POSTGRES_HOST:localhost}:${POSTGRES_PORT:5439}/${POSTGRES_DB:well4you}
spring.datasource.username=${POSTGRES_USER:user}
spring.datasource.password=${POSTGRES_PASSWORD:1234}

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

spring.jpa.properties.hibernate.default_schema=commentservice
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.sql.init.mode=always

server.address=0.0.0.0
server.port=${COMMENT_SERVICE_PORT:8087}
