spring.application.name=api-gateway

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE
#logging.level.org.springframework.security=DEBUG

spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=70MB
spring.servlet.multipart.max-request-size=70MB

spring.datasource.url=jdbc:postgresql://${APIGATEWAY_POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:well4you}
spring.datasource.username=${POSTGRES_USER:user}
spring.datasource.password=${POSTGRES_PASSWORD:1234}

spring.jpa.properties.hibernate.default_schema=apigateway
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.sql.init.mode=always

server.address=0.0.0.0
server.port=${APIGATEWAY_SERVER_PORT:8443}

server.ssl.key-store=classpath:${$SSL_KEYSTORE_NAME:apigateway.jks}
server.ssl.key-store-password=${SSL_KEYSTORE_PWD:password}
server.ssl.key-store-type=${SSL_KEYSTORE_TYPE:JKS}
server.ssl.key-alias=${SSL_KEYSTORE_ALIAS:apigateway}

client.prot=${CLIENT_PROT:http}
client.ip=${CLIENT_IP:localhost}
client.port=${CLIENT_PORT:4200}

otp.service.name=${OTP_SERVICE_NAME:localhost}
otp.service.port=${OTP_SERVICE_PORT:8081}
notification.service.name=${NOTIFICATION_SERVICE_NAME:localhost}
notification.service.port=${NOTIFICATION_SERVICE_PORT:8082}
user.service.name=${USER_SERVICE_NAME:localhost}
user.service.port=${USER_SERVICE_PORT:8089}
image.service.name=${IMAGE_SERVICE_NAME:localhost}
image.service.port=${IMAGE_SERVICE_PORT:8083}
coach.service.name=${COACH_SERVICE_NAME:localhost}
coach.service.port=${COACH_SERVICE_PORT:8085}

admin.email=${ADMIN_EMAIL:manuele@gmail.com}
admin.password=${ADMIN_PASSWORD:password}

spring.security.oauth2.client.registration.google.clientId=${GOOGLE_CLIENT_ID:206891529967-qrahou290ru1r3rjhhb8viqqou3t3o3v.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google.clientSecret=${GOOGLE_CLIENT_SECRET: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}

# Services service route
spring.cloud.gateway.mvc.routes[0].id=services-service
spring.cloud.gateway.mvc.routes[0].uri=http://${SERVICES_SERVICE_NAME:localhost}:${SERVICES_SERVICE_PORT:8084}
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/services/**

# Coach service route
spring.cloud.gateway.mvc.routes[1].id=coach-service
spring.cloud.gateway.mvc.routes[1].uri=http://${COACH_SERVICE_NAME:localhost}:${COACH_SERVICE_PORT:8085}
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/coach/**

# Like service route
spring.cloud.gateway.mvc.routes[2].id=like-service
spring.cloud.gateway.mvc.routes[2].uri=http://${LIKE_SERVICE_NAME:localhost}:${LIKE_SERVICE_PORT:8086}
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/like/**

# Comment service route
spring.cloud.gateway.mvc.routes[3].id=comment-service
spring.cloud.gateway.mvc.routes[3].uri=http://${COMMENT_SERVICE_NAME:localhost}:${COMMENT_SERVICE_PORT:8087}
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/comment/**

# User service route
spring.cloud.gateway.mvc.routes[4].id=shop-service
spring.cloud.gateway.mvc.routes[4].uri=http://${SHOP_SERVICE_NAME:localhost}:${SHOP_SERVICE_PORT:8088}
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/api/shop/**

# User service route
spring.cloud.gateway.mvc.routes[5].id=user-service
spring.cloud.gateway.mvc.routes[5].uri=http://${USER_SERVICE_NAME:localhost}:${USER_SERVICE_PORT:8089}
spring.cloud.gateway.mvc.routes[5].predicates[0]=Path=/api/user/**

# Image service route
spring.cloud.gateway.mvc.routes[6].id=image-service
spring.cloud.gateway.mvc.routes[6].uri=http://${IMAGE_SERVICE_NAME:localhost}:${IMAGE_SERVICE_PORT:8083}
spring.cloud.gateway.mvc.routes[6].predicates[0]=Path=/api/image/**

# Schedule service route
spring.cloud.gateway.mvc.routes[7].id=schedule-service
spring.cloud.gateway.mvc.routes[7].uri=http://${SCHEDULE_SERVICE_NAME:localhost}:${SCHEDULE_SERVICE_PORT:8090}
spring.cloud.gateway.mvc.routes[7].predicates[0]=Path=/api/schedule/**
