package com.coachservice.app.model;

import com.coachservice.app.model.enumerator.DivisionName;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a Division entity within the coach service application.
 * <p>
 * This entity defines the divisions to which coaches can belong. It maps to the "division" table in the database.
 * Each division has a unique identifier and a name that is represented by an enumerated type.
 * </p>
 *
 * <p>Key attributes include:</p>
 * <ul>
 *     <li><b>id:</b> Unique identifier for the division, automatically generated by the database.</li>
 *     <li><b>name:</b> The name of the division, represented as an enumeration to ensure consistency and validity.</li>
 * </ul>
 *
 * <p>The class provides constructors for creating instances of Division and uses Lombok annotations for boilerplate code reduction.</p>
 *
 * @see DivisionName
 */
@Data
@Entity
@AllArgsConstructor
@NoArgsConstructor
public class Division {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private DivisionName name;

    /**
     * Constructs a new Division with the specified name.
     *
     * @param name the name of the division
     */
    public Division(DivisionName name) {
        this.name = name;
    }
}
