package com.coachservice.app.model;

import com.coachservice.app.model.enumerator.PillarName;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a Pillar entity within the coach service application.
 * <p>
 * This entity maps to the "pillar" table in the database and defines the different pillars of specialization
 * that coaches can be associated with. Each pillar has a unique identifier and a name represented as an enumerated type.
 * </p>
 *
 * <p>Key attributes include:</p>
 * <ul>
 *     <li><b>id:</b> The unique identifier for the pillar, automatically generated by the database.</li>
 *     <li><b>name:</b> The name of the pillar, represented using the {@link PillarName} enumeration to ensure consistency.</li>
 * </ul>
 *
 * <p>The class includes constructors for initializing instances of Pillar and uses Lombok annotations to minimize boilerplate code.</p>
 *
 * @see PillarName
 */
@Data
@Entity
@AllArgsConstructor
@NoArgsConstructor
public class Pillar {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private PillarName name;

    /**
     * Constructs a new Pillar with the specified name.
     *
     * @param name the name of the pillar
     */
    public Pillar(PillarName name) {
        this.name = name;
    }
}
