spring.application.name=notification-service

spring.datasource.url=jdbc:postgresql://${NOTIFICATIONSERVICE_POSTGRES_HOST:localhost}:${POSTGRES_PORT:5434}/${POSTGRES_DB:well4you}
spring.datasource.username=${POSTGRES_USER:user}
spring.datasource.password=${POSTGRES_PASSWORD:1234}

spring.jpa.properties.hibernate.default_schema=notificationservice
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.sql.init.mode=always

server.address=0.0.0.0
server.port=${NOTIFICATION_SERVICE_PORT:8082}

spring.mail.host=smtp.gmail.com
spring.mail.port=${WELL4YOU_EMAIL_PORT:465}
spring.mail.username=${WELL4YOU_EMAIL:leonardo.well4you@gmail.com}
spring.mail.password=${WELL4YOU_EMAIL_PASSWORD:ttgy esge zkip ddai}
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=true
