spring.application.name=user-service

spring.datasource.url=jdbc:postgresql://${USERSERVICE_POSTGRES_HOST:localhost}:${POSTGRES_PORT:5441}/${POSTGRES_DB:well4you}
spring.datasource.username=${POSTGRES_USER:user}
spring.datasource.password=${POSTGRES_PASSWORD:1234}

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

spring.jpa.properties.hibernate.default_schema=userservice
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.sql.init.mode=always

server.address=0.0.0.0
server.port=${USER_SERVICE_PORT:8089}
